### PR TITLE
Update installer icon and background

### PR DESCRIPTION
**Pull request by msshhp**
Resolves https://github.com/herondlabs/herond-browser/issues/226

## Submitter Checklist:

- [ ] There is a ticket for my issue
- [ ] Used Github [auto-closing keywords](https://docs.github.com/en/github/managing-your-work-on-github/linking-a-pull-request-to-an-issue) in the PR description above
- [ ] Wrote a good [PR/commit description](https://google.github.io/eng-practices/review/developer/cl-descriptions.html)
- [ ] Added appropriate labels to the associated issue
- [ ] Checked the PR locally
- [ ] Ran `git rebase master` (if needed)

## Reviewer Checklist:

- [ ] Adequate test coverage exists to prevent regressions
- [ ] Major classes, functions and non-trivial code blocks are well-commented
- [ ] Code follows the style guide
- [ ] Test plan is specified in PR before merging

## After-merge Checklist:

- [ ] All relevant documentation has been updated

## Test Plan:

### CODE REVIEW

**Comment by chungphb** [comment]
@nqcuongit95 Please review this PR and resolve the https://github.com/herondlabs/herond-browser/issues/228 issue.

**Comment by minhnd410** [comment]
@nqcuongit95 remind

**Comment by nqcuongit95** [comment]
image
image

Have verified it, LGTM!

**Comment by minhnd410** [comment]
Reopen an accidentally closed

**Pull request merged**
